select COUNT(BUSINESS_ID) from BUSINESS;
select COUNT(B_CAT_ID) from BUSINESS_CATEGORY;
select COUNT(YELP_USER_ID) from YELP_USER;
select COUNT(R_ID) from REVIEW;
select * from YELP_USER;
SELECT TOP 3 * FROM YELP_USER;
select BUSINESS_ID FROM BUSINESS;
select B_CAT_ID from BUSINESS_CATEGORY