-- Find top two businesses, which have highest average ratings in each business category. For
-- each business, list business id, business name and business category name.
CREATE FUNCTION GET_VAL(NAME IN VARCHAR )
    RETURNS VARCHAR
    AS
    BEGIN
SELECT
RETURN (AGE);
END;
/

ALTER TABLE BUSINESS ADD CATEGORY_NAME VARCHAR(20);
UPDATE BUSINESS
SET CATEGORY_NAME = (SELECT C_NAME
                    FROM BUSINESS_CATEGORY CAT
                    WHERE BUSINESS.BCT_ID = CAT.B_CAT_ID
);

SELECT B.CATEGORY_NAME,B.BUSINESS_ID,B.B_NAME, AVG(R.RATING) FROM BUSINESS B, REVIEW R WHERE B.BUSINESS_ID = R.BUSINESS_NO GROUP BY B.CATEGORY_NAME, B.BUSINESS_ID, B.B_NAME

SELECT * FROM (
    SELECT B.CATEGORY_NAME,B.BUSINESS_ID,B.B_NAME, AVG(R.RATING) FROM BUSINESS B, REVIEW R WHERE B.BUSINESS_ID = R.BUSINESS_NO GROUP BY B.CATEGORY_NAME, B.BUSINESS_ID, B.B_NAME
    ) AS RESULT WHERE ;


(
    SELECT  COUNT(*)
    FROM    RESULT RE
    WHERE RE.CATEGORY_NAME = .name AND
            f.score >= s.score
) <= 2
